---
title: "CH16 Hangover"
author: "Paul"
date: '`r format(Sys.Date(), "%d\\. %m\\. %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
extrafont::loadfonts(device = "win")
windowsFonts("Arial_Narrow" = windowsFont("Arial Narrow"))
options(mc.cores = parallel::detectCores())
library(tidyverse)
theme_set(hrbrthemes::theme_ipsum(base_family = "Arial_Narrow"))
```
```{r}
library(rstan)
library(tidybayes)
```

```{r}
df <- rio::import(here::here("data","stan_hangover.csv"))
```
```{r}
df %>% 
  mutate(date = lubridate::ymd(date),
         holiday = factor(holiday)
         ) %>% 
  ggplot(aes(date, volume, color = holiday)) +
  geom_line()
```
```{r}
df %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  ggplot(aes(date, holiday))+
  geom_line()
```
```{r}
ols_model <- stan_model("hangover_regression.stan")
```
```{r}
fit_ols <- sampling(ols_model, compose_data(df))
```

